name: cykero-linnworks
services:
  mongo:
    image: mongo:7.0
    ports:
      - "27077:27017"
    # For dev, running without auth is simplest. If you want auth, uncomment env vars and init.
    environment:
      MONGO_INITDB_DATABASE: cykero-linnworks
      #   MONGO_INITDB_ROOT_USERNAME: dev
      #   MONGO_INITDB_ROOT_PASSWORD: devpass
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "63790:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  mongo-config:
  redis-data: